### Music Guy Configuration ###

# The folder to monitor
musicFolder: "~/Music/"

# Files will be renamed to match the nameTemplate
enableRenamer: false
# How the files should be named within musicFolder
nameTemplate: "%albumartist%/%album%/%title%"

# If true, MongoDB will be used instead of tingoDB
useMongoDB: false
